name: Generate Documentation
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Get Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: Install
        run: poetry install
      - name: Generate Documentation
        run: poetry run pdoc discord_lumberjack --html -o docs/ -f -c show_source_code=False
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Create Pull Request
        if: steps.git-check.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          title: Generate Documentation
          commit-message: generated docs with pdoc3
          branch: documentation
          token: ${{ secrets.PERSONAL_GH_TOKEN }}
          labels: automerge,documentation
