name: Format Code
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Upgrade pip
        run: |
          pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install typing-extensions
      - name: Install black-with-tabs
        run: |
          pip install black-with-tabs
      - name: Format code
        run: |
          black .
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Black With Tabs'
          git config --global user.email 'noreply@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Formatted code (GitHub Action)"
          git push
