name: Format Code
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Upgrade pip
        run: |
          pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install typing-extensions
          pip install mypy-extensions
      - name: Install black-with-tabs
        run: |
          pip install black-with-tabs
      - name: Format code
        run: |
          black .
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Create Pull Request
        if: steps.git-check.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          title: Autoformat code
          commit-message: autoformatted code with black-with-tabs
