name: Format and Document
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Get Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: Install
        run: poetry install

  format:
    name: Format Code
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Format code
        run: poetry run black discord_lumberjack

  documentation:
    name: Generate Documentation
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Generate Documentation
        run: poetry run pdoc discord_lumberjack --html -o docs/ -f -c show_source_code=False

  apply:
    name: Apply Changes
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    needs:
      - format
      - documentation
    steps:
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Create Pull Request
        if: steps.git-check.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          title: Autoformat and Documentation
          commit-message: autoformatted code and generated docs
          branch: post-merge
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge,notest