name: Publish to PyPI
on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Get Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
      - name: Get current version
        id: get-current-version
        run: echo ::set-output name=current-version::$(poetry version -s)
      - name: Close Current Milestone
        uses: Beakyn/gha-close-milestone@v1.1.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository: ${{ github.repository }}
          milestone-title: v${{ steps.get-current-version.outputs.current-version }}
      - name: Bump version
        id: bump-version
        run: |
          poetry version patch
          echo ::set-output name=new-version::$(poetry version -s)
      - name: Create Milestone
        id: create-milestone
        uses: WyriHaximus/github-action-create-milestone@v1.1.0
        with:
          title: v${{ steps.bump-version.outputs.new-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Set version to ${{ steps.get-next-version.outputs.next-version }}
          commit-message: set version to ${{ steps.get-next-version.outputs.next-version }}
          branch: version-${{ steps.get-next-version.outputs.next-version }}
          token: ${{ secrets.PERSONAL_GH_TOKEN }}
          base: main
          labels: automerge
          milestone: ${{ steps.create-milestone.outputs.number }}
