name: Publish to PyPI
on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Upgrade pip
        run: |
          pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
      - name: Get current version
        id: get-current-version
        run: |
          echo ::set-output name=current-version::$(python setup.py --version)
      - name: Close Current Milestone
        uses: Beakyn/gha-close-milestone@v1.1.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository: ${{ github.repository }}
          milestone-title: v${{ steps.get-current-version.outputs.current-version }}
      - name: Get next version
        id: get-next-version
        run: |
          echo ::set-output name=next-version::$(python -c 'from discord_lumberjack import __version__ as v;s=v.rsplit(".",1);print(s[0],".",int(s[1])+1,sep="")')
      - name: Bump version
        run: |
          sed -i 's/^__version__ .*$/__version__ = "${{ steps.get-next-version.outputs.next-version }}"/g' discord_lumberjack/__init__.py
      - name: Create Milestone
        id: create-milestone
        uses: WyriHaximus/github-action-create-milestone@v1.1.0
        with:
          title: v${{ steps.get-next-version.outputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Set version to ${{ steps.get-next-version.outputs.next-version }}
          commit-message: set version to ${{ steps.get-next-version.outputs.next-version }}
          branch: version-${{ steps.get-next-version.outputs.next-version }}
          token: ${{ secrets.PERSONAL_GH_TOKEN }}
          base: main
          labels: automerge
          milestone: ${{ steps.create-milestone.outputs.number }}
