name: Test
on:
  pull_request:
    branches:
      - main
    paths:
      - discord_lumberjack/**
      - tests/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: "! contains(github.event.pull_request.labels.*.name, 'notest')"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Get Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: Install
        run: poetry install
      - name: Run tests
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DISCORD_DM_ID: ${{ secrets.DISCORD_DM_ID }}
          DISCORD_UNTEXTABLE_DM_ID: ${{ secrets.DISCORD_UNTEXTABLE_DM_ID }}
        run: poetry run pytest
